repos:
  # shfmt formatting
  - repo: https://github.com/maxwinterstein/shfmt-py
    rev: v3.7.0.1
    hooks:
      - id: shfmt
        args: ["-w", "-s", "-i", "2"]
        groups: ["format"]

  # Shellcheck linting
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        args: ["--severity=warning"]
        groups: ["lint"]

  # Ruff linting and formatting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.3
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        groups: ["format", "lint"]
      - id: ruff-format
        groups: ["format"]

  # Markdown formatting
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.17
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-gfm
        groups: ["format"]

  # Markdownlint
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.43.0
    hooks:
      - id: markdownlint
        args: ["--fix"]
        groups: ["format"]